### ISSUE TITLE
Remove name-aliasing

### ISSUE THREAD

**Issue by shingarov** [shingarov/MachineArithmetic#163]
Currently "MachineArithmetic" stands for two things: `MachineArithmetic`, and `MachineArithmetic/MachineArithmetic`.  This has been causing confusion, and then more confusion.

**Comment by janvrany** [comment]
I believe we agreed on renaming package "MachineArithmetic" to "Z3": https://github.com/shingarov/MachineArithmetic/pull/133#issuecomment-1768708120

I'll do it once Smalltalks is over.

**Comment by shingarov** [comment]
Yes, we absolutely did agree.  This Issue is more of a "someone will have to get in the chair and actually do it" : - )
